// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Session {
    /// string id = 1;
    /// // bytes secret_hash = 2;
    /// google.protobuf.Timestamp created_at = 3;
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
