// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: user/api.proto

/* eslint-disable */

export const protobufPackage = "user";

export interface CreateUserReq {
  /** The user's display name. */
  name: string;
  /** The user's email address. */
  email: string;
}

export interface CreateUserResp {
  /** The created user. */
  user?: User | undefined;
}

export interface GetUserReq {
  /** The user ID to retrieve. */
  id: string;
}

export interface GetUserResp {
  /** The requested user. */
  user?: User | undefined;
}

export interface User {
  /** Unique identifier for the user. */
  id: string;
  /** The user's display name. */
  name: string;
  /** The user's email address. */
  email: string;
}

function createBaseCreateUserReq(): CreateUserReq {
  return { name: "", email: "" };
}

export const CreateUserReq: MessageFns<CreateUserReq> = {
  fromJSON(object: any): CreateUserReq {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
    };
  },

  toJSON(message: CreateUserReq): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUserReq>, I>>(base?: I): CreateUserReq {
    return CreateUserReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUserReq>, I>>(object: I): CreateUserReq {
    const message = createBaseCreateUserReq();
    message.name = object.name ?? "";
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseCreateUserResp(): CreateUserResp {
  return { user: undefined };
}

export const CreateUserResp: MessageFns<CreateUserResp> = {
  fromJSON(object: any): CreateUserResp {
    return { user: isSet(object.user) ? User.fromJSON(object.user) : undefined };
  },

  toJSON(message: CreateUserResp): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUserResp>, I>>(base?: I): CreateUserResp {
    return CreateUserResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUserResp>, I>>(object: I): CreateUserResp {
    const message = createBaseCreateUserResp();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    return message;
  },
};

function createBaseGetUserReq(): GetUserReq {
  return { id: "" };
}

export const GetUserReq: MessageFns<GetUserReq> = {
  fromJSON(object: any): GetUserReq {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetUserReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserReq>, I>>(base?: I): GetUserReq {
    return GetUserReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserReq>, I>>(object: I): GetUserReq {
    const message = createBaseGetUserReq();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetUserResp(): GetUserResp {
  return { user: undefined };
}

export const GetUserResp: MessageFns<GetUserResp> = {
  fromJSON(object: any): GetUserResp {
    return { user: isSet(object.user) ? User.fromJSON(object.user) : undefined };
  },

  toJSON(message: GetUserResp): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserResp>, I>>(base?: I): GetUserResp {
    return GetUserResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserResp>, I>>(object: I): GetUserResp {
    const message = createBaseGetUserResp();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    return message;
  },
};

function createBaseUser(): User {
  return { id: "", name: "", email: "" };
}

export const User: MessageFns<User> = {
  fromJSON(object: any): User {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User>, I>>(base?: I): User {
    return User.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User>, I>>(object: I): User {
    const message = createBaseUser();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.email = object.email ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
