// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: auth/api.proto

/* eslint-disable */

export const protobufPackage = "auth";

export enum OauthProvider {
  OAUTH_PROVIDER_UNSPECIFIED = 0,
  OAUTH_PROVIDER_GOOGLE = 1,
  OAUTH_PROVIDER_GITHUB = 2,
  UNRECOGNIZED = -1,
}

export function oauthProviderFromJSON(object: any): OauthProvider {
  switch (object) {
    case 0:
    case "OAUTH_PROVIDER_UNSPECIFIED":
      return OauthProvider.OAUTH_PROVIDER_UNSPECIFIED;
    case 1:
    case "OAUTH_PROVIDER_GOOGLE":
      return OauthProvider.OAUTH_PROVIDER_GOOGLE;
    case 2:
    case "OAUTH_PROVIDER_GITHUB":
      return OauthProvider.OAUTH_PROVIDER_GITHUB;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OauthProvider.UNRECOGNIZED;
  }
}

export function oauthProviderToJSON(object: OauthProvider): string {
  switch (object) {
    case OauthProvider.OAUTH_PROVIDER_UNSPECIFIED:
      return "OAUTH_PROVIDER_UNSPECIFIED";
    case OauthProvider.OAUTH_PROVIDER_GOOGLE:
      return "OAUTH_PROVIDER_GOOGLE";
    case OauthProvider.OAUTH_PROVIDER_GITHUB:
      return "OAUTH_PROVIDER_GITHUB";
    case OauthProvider.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Session {
  /** The session token. */
  token: string;
}

export interface CreateSessionReq {
  /** The user ID to create a session for. */
  userId: string;
}

export interface CreateSessionResp {
  /** The created session token. */
  token: string;
}

export interface ValidateSessionReq {
  /** The session token to validate. */
  token: string;
}

export interface ValidateSessionResp {
  /** The user ID associated with the session. */
  userId: string;
  /** Whether the session cookie should be refreshed. */
  shouldRefreshCookie: boolean;
}

export interface DeleteSessionReq {
  /** The session token to delete. */
  token: string;
}

export interface DeleteSessionResp {
}

export interface StartOauthLoginReq {
  /** The OAuth provider to start login with. */
  provider: OauthProvider;
}

export interface StartOauthLoginResp {
  /** OAuth state parameter for CSRF protection. */
  state: string;
  /** Authorization URL to redirect user to. */
  authorizationUrl: string;
  /** Code verifier for PKCE. */
  codeVerifier: string;
}

export interface HandleOauthCallbackReq {
  /** The OAuth provider. */
  provider: OauthProvider;
  /** Authorization code from OAuth callback. */
  code: string;
  /** Code verifier for PKCE. */
  codeVerifier: string;
}

export interface HandleOauthCallbackResp {
  /** The OAuth account ID. */
  accountId: string;
  /** The associated user ID. */
  userId: string;
  /** User's email from OAuth provider. */
  externalUserEmail: string;
  /** User's name from OAuth provider. */
  externalUserName: string;
}

export interface LinkOauthAccountReq {
  /** The OAuth account ID to link. */
  accountId: string;
  /** The user ID to link to. */
  userId: string;
}

export interface LinkOauthAccountResp {
}

export interface GetOauthAccountReq {
  /** The user ID to get OAuth account for. */
  userId: string;
  /** The OAuth provider. */
  provider: OauthProvider;
}

export interface GetOauthAccountResp {
  /** The external user ID from OAuth provider. */
  externalUserId: string;
}

function createBaseSession(): Session {
  return { token: "" };
}

export const Session: MessageFns<Session> = {
  fromJSON(object: any): Session {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: Session): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Session>, I>>(base?: I): Session {
    return Session.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Session>, I>>(object: I): Session {
    const message = createBaseSession();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseCreateSessionReq(): CreateSessionReq {
  return { userId: "" };
}

export const CreateSessionReq: MessageFns<CreateSessionReq> = {
  fromJSON(object: any): CreateSessionReq {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: CreateSessionReq): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSessionReq>, I>>(base?: I): CreateSessionReq {
    return CreateSessionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSessionReq>, I>>(object: I): CreateSessionReq {
    const message = createBaseCreateSessionReq();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseCreateSessionResp(): CreateSessionResp {
  return { token: "" };
}

export const CreateSessionResp: MessageFns<CreateSessionResp> = {
  fromJSON(object: any): CreateSessionResp {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: CreateSessionResp): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSessionResp>, I>>(base?: I): CreateSessionResp {
    return CreateSessionResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSessionResp>, I>>(object: I): CreateSessionResp {
    const message = createBaseCreateSessionResp();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseValidateSessionReq(): ValidateSessionReq {
  return { token: "" };
}

export const ValidateSessionReq: MessageFns<ValidateSessionReq> = {
  fromJSON(object: any): ValidateSessionReq {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: ValidateSessionReq): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateSessionReq>, I>>(base?: I): ValidateSessionReq {
    return ValidateSessionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateSessionReq>, I>>(object: I): ValidateSessionReq {
    const message = createBaseValidateSessionReq();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseValidateSessionResp(): ValidateSessionResp {
  return { userId: "", shouldRefreshCookie: false };
}

export const ValidateSessionResp: MessageFns<ValidateSessionResp> = {
  fromJSON(object: any): ValidateSessionResp {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      shouldRefreshCookie: isSet(object.shouldRefreshCookie)
        ? globalThis.Boolean(object.shouldRefreshCookie)
        : isSet(object.should_refresh_cookie)
        ? globalThis.Boolean(object.should_refresh_cookie)
        : false,
    };
  },

  toJSON(message: ValidateSessionResp): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.shouldRefreshCookie !== false) {
      obj.shouldRefreshCookie = message.shouldRefreshCookie;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateSessionResp>, I>>(base?: I): ValidateSessionResp {
    return ValidateSessionResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateSessionResp>, I>>(object: I): ValidateSessionResp {
    const message = createBaseValidateSessionResp();
    message.userId = object.userId ?? "";
    message.shouldRefreshCookie = object.shouldRefreshCookie ?? false;
    return message;
  },
};

function createBaseDeleteSessionReq(): DeleteSessionReq {
  return { token: "" };
}

export const DeleteSessionReq: MessageFns<DeleteSessionReq> = {
  fromJSON(object: any): DeleteSessionReq {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: DeleteSessionReq): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteSessionReq>, I>>(base?: I): DeleteSessionReq {
    return DeleteSessionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteSessionReq>, I>>(object: I): DeleteSessionReq {
    const message = createBaseDeleteSessionReq();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseDeleteSessionResp(): DeleteSessionResp {
  return {};
}

export const DeleteSessionResp: MessageFns<DeleteSessionResp> = {
  fromJSON(_: any): DeleteSessionResp {
    return {};
  },

  toJSON(_: DeleteSessionResp): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteSessionResp>, I>>(base?: I): DeleteSessionResp {
    return DeleteSessionResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteSessionResp>, I>>(_: I): DeleteSessionResp {
    const message = createBaseDeleteSessionResp();
    return message;
  },
};

function createBaseStartOauthLoginReq(): StartOauthLoginReq {
  return { provider: 0 };
}

export const StartOauthLoginReq: MessageFns<StartOauthLoginReq> = {
  fromJSON(object: any): StartOauthLoginReq {
    return { provider: isSet(object.provider) ? oauthProviderFromJSON(object.provider) : 0 };
  },

  toJSON(message: StartOauthLoginReq): unknown {
    const obj: any = {};
    if (message.provider !== 0) {
      obj.provider = oauthProviderToJSON(message.provider);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StartOauthLoginReq>, I>>(base?: I): StartOauthLoginReq {
    return StartOauthLoginReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartOauthLoginReq>, I>>(object: I): StartOauthLoginReq {
    const message = createBaseStartOauthLoginReq();
    message.provider = object.provider ?? 0;
    return message;
  },
};

function createBaseStartOauthLoginResp(): StartOauthLoginResp {
  return { state: "", authorizationUrl: "", codeVerifier: "" };
}

export const StartOauthLoginResp: MessageFns<StartOauthLoginResp> = {
  fromJSON(object: any): StartOauthLoginResp {
    return {
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      authorizationUrl: isSet(object.authorizationUrl)
        ? globalThis.String(object.authorizationUrl)
        : isSet(object.authorization_url)
        ? globalThis.String(object.authorization_url)
        : "",
      codeVerifier: isSet(object.codeVerifier)
        ? globalThis.String(object.codeVerifier)
        : isSet(object.code_verifier)
        ? globalThis.String(object.code_verifier)
        : "",
    };
  },

  toJSON(message: StartOauthLoginResp): unknown {
    const obj: any = {};
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.authorizationUrl !== "") {
      obj.authorizationUrl = message.authorizationUrl;
    }
    if (message.codeVerifier !== "") {
      obj.codeVerifier = message.codeVerifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StartOauthLoginResp>, I>>(base?: I): StartOauthLoginResp {
    return StartOauthLoginResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartOauthLoginResp>, I>>(object: I): StartOauthLoginResp {
    const message = createBaseStartOauthLoginResp();
    message.state = object.state ?? "";
    message.authorizationUrl = object.authorizationUrl ?? "";
    message.codeVerifier = object.codeVerifier ?? "";
    return message;
  },
};

function createBaseHandleOauthCallbackReq(): HandleOauthCallbackReq {
  return { provider: 0, code: "", codeVerifier: "" };
}

export const HandleOauthCallbackReq: MessageFns<HandleOauthCallbackReq> = {
  fromJSON(object: any): HandleOauthCallbackReq {
    return {
      provider: isSet(object.provider) ? oauthProviderFromJSON(object.provider) : 0,
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      codeVerifier: isSet(object.codeVerifier)
        ? globalThis.String(object.codeVerifier)
        : isSet(object.code_verifier)
        ? globalThis.String(object.code_verifier)
        : "",
    };
  },

  toJSON(message: HandleOauthCallbackReq): unknown {
    const obj: any = {};
    if (message.provider !== 0) {
      obj.provider = oauthProviderToJSON(message.provider);
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.codeVerifier !== "") {
      obj.codeVerifier = message.codeVerifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HandleOauthCallbackReq>, I>>(base?: I): HandleOauthCallbackReq {
    return HandleOauthCallbackReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HandleOauthCallbackReq>, I>>(object: I): HandleOauthCallbackReq {
    const message = createBaseHandleOauthCallbackReq();
    message.provider = object.provider ?? 0;
    message.code = object.code ?? "";
    message.codeVerifier = object.codeVerifier ?? "";
    return message;
  },
};

function createBaseHandleOauthCallbackResp(): HandleOauthCallbackResp {
  return { accountId: "", userId: "", externalUserEmail: "", externalUserName: "" };
}

export const HandleOauthCallbackResp: MessageFns<HandleOauthCallbackResp> = {
  fromJSON(object: any): HandleOauthCallbackResp {
    return {
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      externalUserEmail: isSet(object.externalUserEmail)
        ? globalThis.String(object.externalUserEmail)
        : isSet(object.external_user_email)
        ? globalThis.String(object.external_user_email)
        : "",
      externalUserName: isSet(object.externalUserName)
        ? globalThis.String(object.externalUserName)
        : isSet(object.external_user_name)
        ? globalThis.String(object.external_user_name)
        : "",
    };
  },

  toJSON(message: HandleOauthCallbackResp): unknown {
    const obj: any = {};
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.externalUserEmail !== "") {
      obj.externalUserEmail = message.externalUserEmail;
    }
    if (message.externalUserName !== "") {
      obj.externalUserName = message.externalUserName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HandleOauthCallbackResp>, I>>(base?: I): HandleOauthCallbackResp {
    return HandleOauthCallbackResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HandleOauthCallbackResp>, I>>(object: I): HandleOauthCallbackResp {
    const message = createBaseHandleOauthCallbackResp();
    message.accountId = object.accountId ?? "";
    message.userId = object.userId ?? "";
    message.externalUserEmail = object.externalUserEmail ?? "";
    message.externalUserName = object.externalUserName ?? "";
    return message;
  },
};

function createBaseLinkOauthAccountReq(): LinkOauthAccountReq {
  return { accountId: "", userId: "" };
}

export const LinkOauthAccountReq: MessageFns<LinkOauthAccountReq> = {
  fromJSON(object: any): LinkOauthAccountReq {
    return {
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: LinkOauthAccountReq): unknown {
    const obj: any = {};
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LinkOauthAccountReq>, I>>(base?: I): LinkOauthAccountReq {
    return LinkOauthAccountReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LinkOauthAccountReq>, I>>(object: I): LinkOauthAccountReq {
    const message = createBaseLinkOauthAccountReq();
    message.accountId = object.accountId ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseLinkOauthAccountResp(): LinkOauthAccountResp {
  return {};
}

export const LinkOauthAccountResp: MessageFns<LinkOauthAccountResp> = {
  fromJSON(_: any): LinkOauthAccountResp {
    return {};
  },

  toJSON(_: LinkOauthAccountResp): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LinkOauthAccountResp>, I>>(base?: I): LinkOauthAccountResp {
    return LinkOauthAccountResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LinkOauthAccountResp>, I>>(_: I): LinkOauthAccountResp {
    const message = createBaseLinkOauthAccountResp();
    return message;
  },
};

function createBaseGetOauthAccountReq(): GetOauthAccountReq {
  return { userId: "", provider: 0 };
}

export const GetOauthAccountReq: MessageFns<GetOauthAccountReq> = {
  fromJSON(object: any): GetOauthAccountReq {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      provider: isSet(object.provider) ? oauthProviderFromJSON(object.provider) : 0,
    };
  },

  toJSON(message: GetOauthAccountReq): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.provider !== 0) {
      obj.provider = oauthProviderToJSON(message.provider);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOauthAccountReq>, I>>(base?: I): GetOauthAccountReq {
    return GetOauthAccountReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOauthAccountReq>, I>>(object: I): GetOauthAccountReq {
    const message = createBaseGetOauthAccountReq();
    message.userId = object.userId ?? "";
    message.provider = object.provider ?? 0;
    return message;
  },
};

function createBaseGetOauthAccountResp(): GetOauthAccountResp {
  return { externalUserId: "" };
}

export const GetOauthAccountResp: MessageFns<GetOauthAccountResp> = {
  fromJSON(object: any): GetOauthAccountResp {
    return {
      externalUserId: isSet(object.externalUserId)
        ? globalThis.String(object.externalUserId)
        : isSet(object.external_user_id)
        ? globalThis.String(object.external_user_id)
        : "",
    };
  },

  toJSON(message: GetOauthAccountResp): unknown {
    const obj: any = {};
    if (message.externalUserId !== "") {
      obj.externalUserId = message.externalUserId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOauthAccountResp>, I>>(base?: I): GetOauthAccountResp {
    return GetOauthAccountResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOauthAccountResp>, I>>(object: I): GetOauthAccountResp {
    const message = createBaseGetOauthAccountResp();
    message.externalUserId = object.externalUserId ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
