use anyhow::Result;
use anyhow::anyhow;
use prost_types::FileDescriptorSet;
use protox::compile;
use std::path::Path;

pub fn compile_proto(proto_path: &Path) -> Result<FileDescriptorSet> {
    let dir = proto_path.parent().unwrap();
    let file_str = proto_path
        .file_name()
        .and_then(|s| s.to_str())
        .ok_or_else(|| anyhow!("Invalid proto filename"))?;

    let protos = vec![file_str.to_string()];
    let includes = vec![dir.to_string_lossy().to_string()];

    let fds: FileDescriptorSet = compile(&protos, &includes)
        .map_err(|e| anyhow!("protox compile error on {:?}: {}", proto_path, e))?;

    Ok(fds)
}

pub(crate) fn generate_protos<P: AsRef<Path>>(
    src_dir: P,
    proto_files: &[P],
    current_dir: P,
    package_name: &str,
) {
    let proto_dir = src_dir.as_ref().join("proto");
    std::fs::create_dir_all(&proto_dir).expect("Failed to create proto dir");

    tonic_prost_build::configure()
        .type_attribute(".", "#[derive(serde::Serialize, serde::Deserialize)]")
        .compile_well_known_types(false)
        .extern_path(".google.protobuf.Timestamp", "::prost_wkt_types::Timestamp")
        .out_dir(&proto_dir)
        .compile_protos(&proto_files, &[current_dir])
        .expect("Failed to compile protos");

    let mod_rs_content = format!(
        "// This file is @generated by proto-gen-rs.\ninclude!(\"{}.rs\");\n",
        package_name
    );
    std::fs::write(proto_dir.join("mod.rs"), mod_rs_content).expect("Failed to write mod.rs");
}
