use std::path::Path;

pub(crate) fn generate_protos<P: AsRef<Path>>(
    src_dir: P,
    proto_files: &[P],
    current_dir: P,
    package_name: &str,
) {
    // Create proto subdirectory
    let proto_dir = src_dir.as_ref().join("proto");
    std::fs::create_dir_all(&proto_dir).expect("Failed to create proto dir");

    // Generate proto code into src/proto/
    tonic_prost_build::configure()
        .type_attribute(".", "#[derive(serde::Serialize, serde::Deserialize)]")
        .compile_well_known_types(false)
        .extern_path(".google.protobuf.Timestamp", "::prost_wkt_types::Timestamp")
        .out_dir(&proto_dir)
        .compile_protos(&proto_files, &[current_dir])
        .expect("Failed to compile protos");

    // Create mod.rs that directly includes the generated file
    let mod_rs_content = format!(
        "// This file is @generated by proto-gen-rs.\ninclude!(\"{}.rs\");\n",
        package_name
    );
    std::fs::write(proto_dir.join("mod.rs"), mod_rs_content).expect("Failed to write mod.rs");
}
