set dotenv-load

DATABASE_URL := "postgres://$PG_USER:$PG_PASSWORD@$PG_HOST:$PG_PORT/$PG_DBNAME?sslmode=disable"
DATABASE_NAME := "$PG_DBNAME"
MIGRATIONS_DIR := "migrations"

PROTO_GEN_RS_BINARY := "../../scripts/proto-gen-rs/proto-gen-rs"

generate-protos:
  {{PROTO_GEN_RS_BINARY}}

create:
    psql -h localhost -U postgres -w -c "CREATE DATABASE {{DATABASE_NAME}};"

drop:
    psql -h localhost -U postgres -w -c "DROP DATABASE IF EXISTS {{DATABASE_NAME}};"

migrate-up:
    migrate -path {{MIGRATIONS_DIR}} -database "{{DATABASE_URL}}" up

migrate-down:
    migrate -path {{MIGRATIONS_DIR}} -database "{{DATABASE_URL}}" down

create-migration name:
    migrate create -ext sql -dir {{MIGRATIONS_DIR}} -seq {{name}}

connect:
    psql {{DATABASE_NAME}}
